### ISSUE TITLE
specify license MIT vs. GPL

### ISSUE THREAD

**Issue by alex-rind** [john-guerra/netClusteringJs#12]
On the one hand,  the header of [netClustering.js](https://github.com/john-guerra/netClusteringJs/blob/master/src/netClustering.js) claims a  GNU General Public License.  
On the other hand, [package.json](https://github.com/john-guerra/netClusteringJs/blob/master/package.json) declares a MIT license for the npm package, which is also listed on <https://www.npmjs.com/package/netclustering>.

Since the original work by Robin W. Spencer was released under GPL, which is strong copyleft, this would probably also apply to the npm package (although I am not a lawyer).

**Comment by john-guerra** [comment]
Thanks, good catch!
