### ISSUE TITLE
Is this library no longer applicable to d3 v4?

### ISSUE THREAD

**Issue by metromark** [john-guerra/netClusteringJs#2]
I was prompted an error when I tried using this library.

`TypeError: dataObjList[group[i]] is undefined`

I'm assuming this is due to d3 v4 update, I used this on d3 v3 before and it worked.

**Comment by john-guerra** [comment]
The tool doesn't depend on d3, so it should work with any version. Can you provide a jsfiddle or codepen that reproduces your error? I'm going to close this for now
