### ISSUE TITLE
GET https://unpkg.com/netclustering@0.0.4/dist/netClustering.min.js net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by Benreuveni** [john-guerra/netClusteringJs#9]
Hello,

Including <script src="https://unpkg.com/netclustering/dist/netClustering.min.js"></script> in my HTML head returns GET https://unpkg.com/netclustering@0.0.4/dist/netClustering.min.js net::ERR_ABORTED 404.

Any help would be amazing!

**Comment by john-guerra** [comment]
Hi, so sorry I didn't see this before. Fixing it now

**Comment by john-guerra** [comment]
Fixed in version 0.0.7 please let me know if it works now @Benreuveni
